### ISSUE TITLE
es-exporter.py中某处api与最新版本不匹配

### ISSUE THREAD

**Issue by zhongyang180** [stevapple/elasticsearch-utils#6]
82-88行的api已经发生了变动。

将elasticsearch包回退到7.x最高版本时报错为 
ImportError: cannot import name 'AsyncElasticsearch' from 'elasticsearch'
将elasticsearch包升级到8.0以上版本时报错为
TypeError: AsyncElasticsearch.__init__() got an unexpected keyword argument 'host'

**Comment by stevapple** [comment]
麻烦确认一下 #7 是否已经修复？
